#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Remove local files generated by tests/verifiers.
Safe to run before packaging a release ZIP.
"""
from __future__ import annotations
from pathlib import Path
import shutil

PATTERNS = [
    '__pycache__', '.pytest_cache', 'appdb*', 'audit_v*', 'LIVE_CORE_AUDIT*', 'ui_audit*', 'REAL_COMPLEX_REPORTS*',
    'SAAS_UI_*.png', 'USER_FRIENDLY_VERIFY_*.json', 'SAAS_UI_VERIFY_*.json', 'UI_BROWSER_SMOKE_*.json', 'COMPLETE_UIUX_VERIFY_*.json', 'COMPLEX_CASE_*.json', 'COMPLEX_CASE_*.md', 'AUDIT_REPORT*.md', 'TRAINER_MAX_UX_VERIFY_*.json', 'LANGUAGE_STYLE_*',
    'REPORT_CORE_v8_6_*.md', 'USER_ACCEPTANCE_*.md', 'USER_ACCEPTANCE_VERIFY_*.json',
    'REFERENCE_INTERVIEW_VERIFY_*.json', 'ALL_TECH_REPORT*.md', 'COMPLEX_E2E_*.md',
    'CONTEXTUAL_CLARIFICATIONS_*.md', 'DEEP_SCHEMA_VALIDATION_*.md', 'LAYOUT_NO_OVERLAP_*.md',
    'REAL_USER_FLOW_*.md', 'SCHEMA_VALIDATION_*.md', 'USER_REPORT_*.md', 'real_user_*.png', 'real_user_*.txt',
    '*.pyc', '*.pyo', '*.sqlite3', '*.sqlite', '*.db', '*.png', '*.jpg', '*.jpeg', '*.webp',
]

def main() -> int:
    root = Path(__file__).resolve().parent
    removed = 0
    for pat in PATTERNS:
        for p in list(root.glob(pat)) + list(root.rglob(pat)):
            if not p.exists() or '.git' in p.parts:
                continue
            if p.is_dir():
                shutil.rmtree(p, ignore_errors=True)
                removed += 1
            elif p.is_file():
                p.unlink()
                removed += 1
    print(f'clean_generated_artifacts: removed={removed}')
    return 0

if __name__ == '__main__':
    raise SystemExit(main())
