# -*- coding: utf-8 -*-
"""Каталог архитектурных инвариантов v7.6.

Инвариант — это проверка, которую нельзя забывать при проектировании
интеграции. В отличие от частного правила, инвариант формулирует общий
принцип: ключи должны иметь область уникальности, событие должно иметь
конверт, retry должен быть идемпотентным, внешняя зависимость должна иметь
деградацию и т.д.

Каталог намеренно широкий. Он не претендует на математически полный список
всех возможных ошибок в любых системах, но покрывает основные классы
производственных дефектов в интеграциях, API, event-driven потоках,
финансовых/регуляторных процессах, DWH, миграциях и эксплуатации.
"""
from __future__ import annotations
import re


def _s(x):
    return str(x or '').strip()


def _low(x):
    return _s(x).lower()


def _blob(model):
    meta = model.get('meta') or {}
    steps = model.get('steps') or []
    systems = model.get('systems') or {}
    return ' '.join([
        _low(meta.get('name')), _low(meta.get('entity')), _low(meta.get('goal')),
        _low(meta.get('description')), _low(meta.get('lookup_keys')), _low(meta.get('constraints')),
        ' '.join(_low(f.get('name')) + ' ' + _low(f.get('type')) for f in meta.get('fields', [])),
        ' '.join(_low(s.get('name')) + ' ' + _low(s.get('channel')) + ' ' + _low(s.get('data_in')) + ' ' + _low(s.get('data_out')) + ' ' + _low(s.get('compensation')) for s in steps),
        ' '.join(_low(k) + ' ' + _low(v.get('role')) + ' ' + _low(v.get('owner')) for k, v in systems.items()),
    ])


def _probe(status, area, title, question, why, how, examples=None, code=None):
    return {
        'status': status,
        'area': area,
        'title': title,
        'question': question,
        'why': why,
        'how': how,
        'examples': examples or [],
        'code': code or '',
    }


# scope:
# base, data, writes, events, kafka, async, sync, external, webhook, file_batch,
# money, regulatory, sensitive, highload, customer, multitenant, legacy, dwh,
# read, db, migration, security, observability, operations.
INVARIANT_CATALOG = [
    # ----------------------- бизнес и границы процесса --------------------
    dict(code='BIZ-001', scope='base', area='Бизнес и границы', title='У процесса должен быть явно определён успешный финал.', question='Что считается успешным завершением процесса и какой результат видит потребитель?', why='Без финала команда реализует шаги, но не понимает, когда процесс действительно завершён.', how='Опишите финальный бизнес-результат, финальные статусы, владельца результата и критерий готовности.', evidence=r'цель|успех|финальн|completed|done|result|результат', examples=['финальный статус COMPLETED', 'создана операция в системе-получателе']),
    dict(code='BIZ-002', scope='base', area='Бизнес и границы', title='Границы ответственности систем должны быть зафиксированы.', question='Какая система владеет процессом, данными, контрактом и ошибками?', why='Без границ ответственности спорные ошибки будут перекладываться между командами.', how='Назначьте владельца процесса, владельца каждой системы, владельца контракта и правила эскалации.', evidence=r'owner|владел|ответствен|эскалац|support'),
    dict(code='BIZ-003', scope='base', area='Бизнес и границы', title='Процесс должен разделять обязательные и необязательные шаги.', question='Какие шаги блокируют бизнес-результат, а какие могут быть выполнены позже?', why='Необязательные обогащения часто случайно попадают в критический путь и ломают SLA.', how='Для каждого шага укажите mandatory/optional и допустимую деградацию.', evidence=r'обязательн|optional|необязатель|degrad|деград|fallback'),
    dict(code='BIZ-004', scope='base', area='Бизнес и границы', title='Должен быть понятен инициатор и потребитель результата.', question='Кто запускает процесс и кто использует результат: клиент, оператор, система, batch или регулятор?', why='От инициатора зависит SLA, ошибки, права доступа, UX и требования к статусам.', how='Укажите actor, channel, expected response и способ получения финального результата.', evidence=r'инициатор|actor|client|клиент|оператор|потребител|consumer'),
    dict(code='BIZ-005', scope='base', area='Бизнес и границы', title='Нужно отличать команду от события.', question='Шаг просит систему что-то сделать или только сообщает о уже случившемся факте?', why='Путаница command/event приводит к неверной идемпотентности, ответственности и повторной обработке.', how='Команды называйте в повелительном стиле, события — в прошедшем времени; зафиксируйте владельца команды и владельца факта.', evidence=r'command|команд|event|событ|created|changed|сделать|изменил'),
    dict(code='BIZ-006', scope='base', area='Бизнес и границы', title='Нужно фиксировать бизнес-инварианты, которые нельзя нарушать.', question='Какие условия должны быть истинны всегда, даже при retry, сбоях и ручных исправлениях?', why='Технически успешный процесс может нарушить бизнес-ограничение: двойное списание, неверный статус, повторная отправка.', how='Составьте список invariants: не более одной активной операции, сумма проводок сходится, финальный статус не откатывается без компенсации.', evidence=r'invariant|инвариант|нельзя|запрещ|не более|constraint|огранич'),
    dict(code='BIZ-007', scope='base', area='Бизнес и границы', title='Процесс должен иметь owner ручных решений.', question='Кто принимает решение при спорном статусе, конфликте данных или частичном отказе?', why='Без владельца ручной разбор становится бесконечным зависанием в промежуточном состоянии.', how='Опишите роли поддержки, back-office, технического владельца и SLA ручного разбора.', evidence=r'ручн|manual|back.?office|разбор|оператор|support'),
    dict(code='BIZ-008', scope='base', area='Бизнес и границы', title='Нужно определить допустимый уровень eventual consistency.', question='Сколько времени разные системы могут видеть разные состояния одной сущности?', why='Асинхронная архитектура всегда создаёт окно рассогласования, которое нужно согласовать с бизнесом.', how='Укажите freshness/SLA согласованности для потребителей, витрин и статусов.', evidence=r'eventual|согласован|freshness|актуальн|задержк|лаг'),

    # ----------------------- идентичность и ключи -------------------------
    dict(code='ID-001', scope='data', area='Идентичность и ключи', title='Каждый идентификатор должен иметь область уникальности.', question='Где именно уникален requestId, operationId, externalId или providerEventId?', why='Одинаковый id может быть допустим в разных типах операций, tenant, провайдерах или целевых системах.', how='Зафиксируйте scope: global, per-source, per-provider, per-operationType, per-targetSystem, per-tenant, per-process.', evidence=r'scope|област.*уник|operation.?type|target.?system|source.?system|tenant|provider|тип.*операц', examples=['operUid + operationType + targetSystem', 'providerEventId + providerCode']),
    dict(code='ID-002', scope='data', area='Идентичность и ключи', title='Business key, lookup key и idempotency key должны быть согласованы.', question='Одинаковые ли поля используются для поиска, upsert, дедупликации и replay?', why='Если ключи отличаются, retry может не создать дубль, но обновить не ту запись.', how='Составьте таблицу соответствия businessKey / lookupKey / idempotencyKey / replayKey / uniqueIndex.', evidence=r'business.?key|lookup.?key|idempotency|unique|уникальн|ключ поиска'),
    dict(code='ID-003', scope='data', area='Идентичность и ключи', title='Внешний идентификатор не должен считаться глобально уникальным без доказательства.', question='От какого источника пришёл externalId и может ли он пересекаться с другим источником?', why='Провайдеры часто гарантируют уникальность только внутри своей системы или договора.', how='Добавьте sourceSystem/providerCode в составной ключ и в контракт события.', evidence=r'external.?id|provider.?id|source.?system|provider|внешн.*id'),
    dict(code='ID-004', scope='multitenant', area='Идентичность и ключи', title='В multi-tenant контуре ключи должны включать tenant scope.', question='Используется ли tenantId во всех SELECT, UPDATE, UNIQUE, кешах и событиях?', why='Без tenantId возможна утечка данных и пересечение записей разных клиентов.', how='Включите tenantId в ключи, индексы, ACL, логи и метрики.', evidence=r'tenant.?id|tenant|мультитенант|арендатор'),
    dict(code='ID-005', scope='events', area='Идентичность и ключи', title='EventId должен отличаться от aggregateId.', question='Есть ли отдельный eventId для дедупликации события и aggregateId для бизнес-сущности?', why='Одно и то же событие и одна и та же сущность имеют разный жизненный цикл.', how='В event envelope заведите eventId, aggregateId/entityId и correlationId как разные поля.', evidence=r'event.?id.*aggregate|aggregate.?id.*event|event.?id|aggregate.?id'),
    dict(code='ID-006', scope='base', area='Идентичность и ключи', title='CorrelationId не должен использоваться как ключ идемпотентности.', question='CorrelationId нужен для трассировки или для дедупликации?', why='Один correlationId может объединять несколько разных операций внутри одного процесса.', how='Используйте correlationId для поиска цепочки, а operationId/idempotencyKey — для защиты от дублей.', evidence=r'correlation.?id|tracking.?id|trace.?id'),
    dict(code='ID-007', scope='writes', area='Идентичность и ключи', title='Уникальный индекс должен соответствовать бизнес-уникальности.', question='Какие поля реально запрещают создать дубль операции?', why='Проверка в коде без уникального индекса проигрывает гонку при параллельных запросах.', how='Добавьте UNIQUE/partial UNIQUE индекс на business key или idempotency key.', evidence=r'unique|уникальн.*индекс|constraint|ограничен'),
    dict(code='ID-008', scope='base', area='Идентичность и ключи', title='Ключи не должны зависеть от изменяемых полей.', question='Есть ли в ключе поля, которые могут быть исправлены, нормализованы или переименованы?', why='Изменение поля-части ключа ломает ссылки, replay и аудит.', how='Используйте стабильные идентификаторы; изменяемые атрибуты храните отдельно.', evidence=r'immutable|стабильн|неизмен|surrogate|uuid'),
    dict(code='ID-009', scope='external', area='Идентичность и ключи', title='Должен быть mapping внутренних и внешних идентификаторов.', question='Где хранится связь internalId ↔ externalId и что происходит при повторной регистрации?', why='Без mapping невозможно расследовать ошибки внешней системы и безопасно повторять запросы.', how='Заведите таблицу mapping с sourceSystem, externalId, internalId, status, timestamps.', evidence=r'mapping|маппинг|external.?id|internal.?id|сопостав'),
    dict(code='ID-010', scope='async', area='Идентичность и ключи', title='Replay должен использовать тот же scope, что и обычная обработка.', question='По каким ключам выбирается запись для повторной обработки?', why='Replay по неполному ключу может переиграть не ту подоперацию.', how='Используйте тот же составной ключ, что в Inbox/Outbox/уникальном индексе.', evidence=r'replay|переигр|повторн.*обработ'),

    # ----------------------- контракты и семантика ------------------------
    dict(code='CON-001', scope='events', area='Контракты', title='Каждое событие должно иметь стандартный envelope.', question='Есть ли eventId, eventType, eventVersion, aggregateId, correlationId, occurredAt и producer?', why='Без envelope событие трудно дедуплицировать, трассировать, версионировать и переигрывать.', how='Утвердите единый envelope для всех событий и контрактные тесты.', evidence=r'event.?id|event.?type|event.?version|occurred.?at|aggregate.?id|producer'),
    dict(code='CON-002', scope='events', area='Контракты', title='Событийный контракт должен иметь версию и правила совместимости.', question='Какие изменения считаются backward-compatible и кто проверяет совместимость?', why='Потребители ломаются не только от удаления поля, но и от изменения enum, nullable, формата даты.', how='Используйте Schema Registry/JSON Schema/Avro/Protobuf, versioning и compatibility checks.', evidence=r'schema|registry|json schema|avro|protobuf|version|верси|compatible|совместим'),
    dict(code='CON-003', scope='sync', area='Контракты', title='API должен иметь контракт ошибок.', question='Какие errorCode, retryable, userMessage и technicalMessage возвращаются?', why='Без модели ошибок потребители неправильно повторяют запросы и показывают пользователю неясные сообщения.', how='Опишите Problem+JSON/gRPC status, бизнес-коды ошибок, retryable и correlationId.', evidence=r'error.?code|problem\+json|код ошиб|retryable|grpc status'),
    dict(code='CON-004', scope='base', area='Контракты', title='Контракт должен описывать nullable и обязательность полей.', question='Какие поля required, optional, nullable и когда они появляются?', why='Неявный null часто ломает потребителей сильнее, чем отсутствие нового поля.', how='Зафиксируйте required/optional/nullable, значения по умолчанию и миграционный период.', evidence=r'required|optional|nullable|null|обязательн'),
    dict(code='CON-005', scope='base', area='Контракты', title='Enum должен иметь жизненный цикл.', question='Что делает потребитель при неизвестном enum/status/type?', why='Добавление нового значения enum может сломать старого потребителя.', how='Опишите unknown/default handling, deprecated values и contract tests.', evidence=r'enum|unknown|deprecated|статус|тип'),
    dict(code='CON-006', scope='base', area='Контракты', title='Денежные и количественные поля должны иметь точность и единицы измерения.', question='Какая валюта, масштаб, округление и единица измерения используются?', why='decimal/float, копейки/рубли и разные rounding modes создают финансовые расхождения.', how='Используйте decimal/numeric, amount+currency, scale, rounding mode и тесты границ.', evidence=r'amount|currency|валют|копе|decimal|numeric|округл|scale'),
    dict(code='CON-007', scope='base', area='Контракты', title='Время в контракте должно быть однозначным.', question='Какие поля означают факт, публикацию, получение и обработку; какая timezone?', why='Ошибки времени ломают SLA, сортировку, сверки и регуляторные отчёты.', how='Разделите occurredAt, producedAt, receivedAt, processedAt; используйте UTC/offset.', evidence=r'occurred.?at|produced.?at|received.?at|processed.?at|utc|timezone|таймзон'),
    dict(code='CON-008', scope='base', area='Контракты', title='Контракт должен иметь владельца и процесс изменения.', question='Кто согласует изменение контракта и как уведомляются потребители?', why='Без change process новое поле или статус может сломать production.', how='Назначьте owner, approval flow, changelog, deprecation policy и consumer notification.', evidence=r'owner|владел|change|изменен|deprecat|changelog'),
    dict(code='CON-009', scope='events', area='Контракты', title='Событие должно быть фактом, а не скрытой командой.', question='Название события описывает уже произошедший факт?', why='Event-as-command смешивает ответственность и приводит к непредсказуемым side effects.', how='Именуйте события в прошедшем времени: StatusChanged, PaymentReserved; команды — отдельно.', evidence=r'changed|created|updated|зарегистрирован|создан|изменен'),
    dict(code='CON-010', scope='base', area='Контракты', title='Payload должен иметь ограничения размера.', question='Какой максимальный размер запроса, ответа и события?', why='Большие payload ухудшают latency, storage, broker throughput и DLQ/replay.', how='Зафиксируйте max size, compression, ссылку на объектное хранилище для больших документов.', evidence=r'max.*size|размер|payload|compression|сжат|object storage|s3'),

    # ----------------------- сценарии и статусы --------------------------
    dict(code='SCN-001', scope='base', area='Сценарии и статусы', title='Happy path должен быть описан пошагово.', question='Какие действия выполняются, кто вызывает кого и какой результат каждого шага?', why='Без пошагового сценария разработчики додумывают разные варианты реализации.', how='Сформируйте основной поток: actor, action, input, output, status, side effects.', evidence=r'happy|основн.*сценар|шаг|flow|поток'),
    dict(code='SCN-002', scope='base', area='Сценарии и статусы', title='Для каждого шага должен быть error-flow.', question='Что происходит при validation error, timeout, 4xx/5xx, duplicate, conflict и retry exhausted?', why='Большинство production-инцидентов живут не в happy path.', how='На каждый шаг добавьте таблицу ошибок: причина, статус процесса, retry, компенсация, алерт.', evidence=r'error|ошиб|timeout|таймаут|duplicate|дубл|conflict|конфликт'),
    dict(code='SCN-003', scope='async', area='Сценарии и статусы', title='Асинхронный процесс должен иметь промежуточные и финальные статусы.', question='Какие статусы видит клиент/потребитель, пока обработка не завершена?', why='Без статусов процесс выглядит как пропавшая заявка.', how='Опишите state machine с terminal/retryable/manual statuses.', evidence=r'status|статус|terminal|финальн|processing|manual'),
    dict(code='SCN-004', scope='base', area='Сценарии и статусы', title='Финальный статус должен быть защищён от случайного отката.', question='Можно ли событием или retry перевести COMPLETED/REJECTED обратно в PROCESSING?', why='Запоздалые события могут испортить уже финализированный процесс.', how='Добавьте terminal-state guard и правила допустимых переходов.', evidence=r'terminal|финальн|allowed transition|переход|state machine'),
    dict(code='SCN-005', scope='base', area='Сценарии и статусы', title='Отмена процесса должна быть отдельным сценарием.', question='Что происходит, если пользователь, оператор или система отменяет процесс?', why='Cancel почти всегда отличается от failed и rejected.', how='Опишите CANCEL_REQUESTED/CANCELLED, компенсации, запрет отмены после финального статуса.', evidence=r'cancel|отмен|аннулир'),
    dict(code='SCN-006', scope='external', area='Сценарии и статусы', title='Частичный успех внешней операции должен быть описан.', question='Что делать, если внешняя система выполнила действие, но ответ потерялся?', why='Это классический источник дублей и спорных состояний.', how='Используйте idempotency key, status inquiry API, reconciliation и manual review.', evidence=r'partial|частич|status inquiry|провер.*статус|unknown'),
    dict(code='SCN-007', scope='async', area='Сценарии и статусы', title='Должен быть сценарий “зависло в промежуточном статусе”.', question='Как найти и восстановить сущность, которая слишком долго находится в PROCESSING?', why='Без status aging процесс может зависнуть навсегда.', how='Добавьте SLA по статусам, job поиска зависших, алерт и recovery action.', evidence=r'status aging|завис|stuck|sla.*статус|aging'),
    dict(code='SCN-008', scope='base', area='Сценарии и статусы', title='Ручное исправление должно оставлять след.', question='Что происходит, если оператор вручную меняет статус или данные?', why='Ручное исправление без аудита ломает расследование и сверки.', how='Логируйте actor, reason, old/new value, timestamp и correlationId.', evidence=r'ручн|manual|reason|old value|new value|audit|аудит'),

    # ----------------------- consistency and transactions -----------------
    dict(code='DAT-001', scope='writes', area='Целостность данных', title='У сущности должен быть system of record.', question='Какая система является источником истины и кто имеет право менять состояние?', why='Несколько писателей создают потерянные обновления и расхождения.', how='Назначьте владельца записи; остальные системы отправляют команды или читают проекции.', evidence=r'system of record|source of truth|источник истины|владел.*данн'),
    dict(code='DAT-002', scope='writes', area='Целостность данных', title='Запись и публикация события должны быть атомарно связаны.', question='Есть ли Outbox при изменении БД и отправке события?', why='Без Outbox событие может потеряться или появиться без записи.', how='Используйте Transactional Outbox и publisher с retry.', evidence=r'outbox|transactional outbox'),
    dict(code='DAT-003', scope='writes', area='Целостность данных', title='Входящее событие должно дедуплицироваться до бизнес-обработки.', question='Есть ли Inbox/unique key перед изменением состояния?', why='At-least-once доставка означает нормальные дубли.', how='Сначала вставьте ключ в Inbox, затем выполняйте бизнес-логику.', evidence=r'inbox|dedup|дедуп|providerEventId'),
    dict(code='DAT-004', scope='writes', area='Целостность данных', title='Конкурентные обновления должны быть защищены.', question='Есть ли version/revision/optimistic locking или сериализация команд?', why='Параллельные обработчики могут перезаписать результат друг друга.', how='Используйте optimistic locking, compare-and-set или serial execution по ключу.', evidence=r'version|revision|optimistic|lock|compare.?and.?set|etag'),
    dict(code='DAT-005', scope='writes', area='Целостность данных', title='Операция должна быть либо атомарной, либо компенсируемой.', question='Что происходит, если сбой случился между двумя пишущими шагами?', why='Частично выполненная распределённая операция оставляет разные системы в разных состояниях.', how='Опишите Saga, компенсации, retry policy и manual recovery.', evidence=r'saga|компенсац|compensation|rollback|manual recovery'),
    dict(code='DAT-006', scope='writes', area='Целостность данных', title='Read-your-writes после async-записи должен быть явно запрещён или обеспечен.', question='Есть ли запрос, который сразу читает результат ещё не обработанного события?', why='После события потребитель может ещё не обновить read-model.', how='Возвращайте trackingId/status или используйте синхронную запись в источник истины.', evidence=r'read.?your.?writes|read model|projection|tracking'),
    dict(code='DAT-007', scope='writes', area='Целостность данных', title='Должна быть история изменений статуса.', question='Можно ли восстановить последовательность переходов по сущности?', why='Последнее состояние не объясняет, почему и где процесс сломался.', how='Добавьте status_history/step_log с actor, reason, old/new status, timestamp.', evidence=r'status_history|step_log|history|истори.*статус|журнал шаг'),
    dict(code='DAT-008', scope='db', area='Целостность данных', title='Схема БД должна соответствовать кардинальности связей.', question='Где один-к-одному, один-ко-многим и многие-ко-многим?', why='Неверная кардинальность приводит к дублям, потерянным данным и сложным миграциям.', how='Зафиксируйте ER-модель, FK/unique constraints и правила удаления.', evidence=r'foreign key|fk|one-to-many|кардинальн|связ'),
    dict(code='DAT-009', scope='writes', area='Целостность данных', title='Удаление должно быть логическим или аудируемым там, где нужен след.', question='Можно ли физически удалять запись или нужен soft delete?', why='Физическое удаление ломает аудит, сверки и replay.', how='Используйте deleted_at/status + retention policy; физическую очистку делайте регламентно.', evidence=r'soft delete|deleted_at|удален|retention|ttl'),
    dict(code='DAT-010', scope='events', area='Целостность данных', title='Событие должно публиковаться после фиксации факта.', question='Событие сообщает о состоянии, которое уже сохранено?', why='Раннее событие может привести потребителя к чтению ещё несуществующих данных.', how='Публикуйте из Outbox после commit; избегайте event before commit.', evidence=r'commit|after commit|outbox|после транзакц'),

    # ----------------------- async/event streaming ------------------------
    dict(code='ASY-001', scope='async', area='Асинхронность и брокеры', title='Async-шаг должен иметь DLQ или карантин.', question='Куда попадает сообщение после исчерпания попыток?', why='Иначе poison message теряется или бесконечно крутится.', how='Настройте max attempts, backoff, DLQ/quarantine, owner и alert.', evidence=r'dlq|dead.?letter|карантин|max attempts|лимит попыт'),
    dict(code='ASY-002', scope='async', area='Асинхронность и брокеры', title='Replay должен быть безопасным и идемпотентным.', question='Можно ли повторно обработать DLQ, период или конкретную сущность без дублей?', why='Replay часто запускается после инцидента и может умножить ущерб.', how='Опишите replay command, права запуска, dry-run, idempotency и reconciliation после replay.', evidence=r'replay|переигр|повторн.*обработ|dry.?run'),
    dict(code='ASY-003', scope='kafka', area='Асинхронность и брокеры', title='Offset должен коммититься только после успешной обработки.', question='Когда consumer фиксирует offset?', why='Commit до обработки приводит к потере сообщения при падении.', how='Коммитьте после транзакционной обработки или используйте outbox/inbox в sink.', evidence=r'commit offset|offset|ack|acknowledg'),
    dict(code='ASY-004', scope='kafka', area='Асинхронность и брокеры', title='Partition key должен соответствовать требованию порядка.', question='По какому ключу партиционируются события?', why='Без правильного ключа события одной сущности могут прийти out-of-order.', how='Используйте entityId/aggregateId как partition key там, где нужен per-entity ordering.', evidence=r'partition|key|партиц|entity.?id|aggregate.?id'),
    dict(code='ASY-005', scope='kafka', area='Асинхронность и брокеры', title='Нужно учитывать hot partitions.', question='Может ли один ключ получить непропорционально много событий?', why='Горячая партиция ограничит throughput всего потока.', how='Измеряйте распределение ключей, используйте salting/шардирование там, где порядок не критичен.', evidence=r'hot partition|горяч.*партиц|salting|skew'),
    dict(code='ASY-006', scope='async', area='Асинхронность и брокеры', title='Потребитель должен иметь backpressure.', question='Что происходит, если downstream БД или API стал медленным?', why='Без backpressure lag и очереди растут до отказа.', how='Ограничьте concurrency, настройте rate limit, circuit breaker и pause/resume consumption.', evidence=r'backpressure|pause|resume|concurrency|параллел|rate limit'),
    dict(code='ASY-007', scope='events', area='Асинхронность и брокеры', title='Late events должны иметь политику обработки.', question='Что делать с событием, пришедшим после более нового состояния?', why='Позднее событие может откатить корректный статус.', how='Используйте sequence/version/event time и stale-event policy.', evidence=r'late event|stale|sequence|version|watermark|устарев'),
    dict(code='ASY-008', scope='events', area='Асинхронность и брокеры', title='Consumer должен быть готов к неизвестной версии события.', question='Что делает потребитель с новой/старой версией?', why='Rolling deployment создаёт период разных версий producer/consumer.', how='Поддерживайте backward compatibility и unknown-field tolerant parsing.', evidence=r'backward|compat|unknown field|верси'),
    dict(code='ASY-009', scope='async', area='Асинхронность и брокеры', title='Retention топика должен покрывать время восстановления.', question='Сколько хранится сообщение и можно ли восстановиться после простоя?', why='Если retention меньше окна восстановления, replay из брокера невозможен.', how='Укажите retention по топикам, DLQ и outbox/inbox.', evidence=r'retention|хранени|ttl'),
    dict(code='ASY-010', scope='async', area='Асинхронность и брокеры', title='Нужно различать retryable и non-retryable ошибки.', question='Какие ошибки повторяются, а какие сразу уходят в reject/manual?', why='Повтор валидационной ошибки создаёт шум и лаг.', how='Классифицируйте validation/business/technical errors и разные маршруты обработки.', evidence=r'retryable|non.?retryable|валидац|business error|technical error'),
    dict(code='ASY-011', scope='events', area='Асинхронность и брокеры', title='Событие должно иметь owner-потребителей или явную модель подписки.', question='Кто является обязательным потребителем события и кто может подписываться свободно?', why='Неизвестные потребители усложняют изменение контракта.', how='Ведите каталог producer/consumer, SLA доставки и compatibility matrix.', evidence=r'consumer|потребител|subscriber|подписчик|catalog'),
    dict(code='ASY-012', scope='events', area='Асинхронность и брокеры', title='Event storm должен быть ограничен.', question='Может ли одно событие породить каскад событий и циклическую обработку?', why='Циклы событий создают лавину сообщений и дубли.', how='Опишите causationId, дедупликацию, запрет циклов и лимиты fan-out.', evidence=r'causation.?id|fan.?out|цикл|event storm'),

    # ----------------------- sync/API -------------------------------------
    dict(code='API-001', scope='sync', area='Синхронные API', title='Каждый блокирующий вызов должен иметь timeout.', question='Какой timeout и общий deadline у вызова?', why='Без timeout поток может зависнуть бесконечно.', how='Распределите timeout budget от пользовательского SLA и задайте deadline propagation.', evidence=r'timeout|deadline|таймаут'),
    dict(code='API-002', scope='sync', area='Синхронные API', title='Retry синхронного API должен быть ограничен и безопасен.', question='Какие HTTP/gRPC ошибки повторяются и сколько раз?', why='Без лимитов retry усиливает аварию зависимости.', how='Используйте capped retry, exponential backoff, jitter и idempotency key.', evidence=r'retry|backoff|jitter|idempotency'),
    dict(code='API-003', scope='external', area='Синхронные API', title='Для внешнего вызова нужен circuit breaker.', question='Когда система перестаёт ходить во внешнюю зависимость?', why='Иначе деградация партнёра истощит ваши потоки.', how='Настройте closed/open/half-open, fallback и метрики breaker state.', evidence=r'circuit|breaker|half.?open|fallback'),
    dict(code='API-004', scope='external', area='Синхронные API', title='Для внешнего вызова нужен bulkhead.', question='Изолирован ли пул потоков/соединений внешней зависимости?', why='Один медленный партнёр может занять весь worker pool.', how='Выделите отдельный connection/thread pool и лимиты concurrency.', evidence=r'bulkhead|pool|пул|concurrency|изоляц'),
    dict(code='API-005', scope='sync', area='Синхронные API', title='API должен быть идемпотентен для повторяемых команд.', question='Что происходит при повторе POST/command после timeout?', why='Клиент не знает, выполнилась ли операция, и может повторить запрос.', how='Добавьте Idempotency-Key, operationId и status inquiry.', evidence=r'idempotency|идемпот|operation.?id|status inquiry'),
    dict(code='API-006', scope='sync', area='Синхронные API', title='Нужна политика rate limiting.', question='Как ограничиваются клиенты, системы и внешние вызовы?', why='Без лимитов один потребитель может перегрузить сервис.', how='Добавьте per-client/per-tenant limits, 429 contract и backoff.', evidence=r'rate.?limit|429|лимит'),
    dict(code='API-007', scope='sync', area='Синхронные API', title='Нужно ограничение размера запроса и ответа.', question='Какой max body size и что делать с большими документами?', why='Большие тела создают OOM, медленные запросы и сетевые таймауты.', how='Валидируйте размер, используйте streaming/object storage для файлов.', evidence=r'max.*body|size|размер|streaming'),
    dict(code='API-008', scope='customer', area='Синхронные API', title='Клиентский ответ должен быть понятным при async-обработке.', question='Что возвращается клиенту, если финальный результат будет позже?', why='Пользователь не должен видеть технический timeout вместо статуса обработки.', how='Возвращайте 202/trackingId/status endpoint и понятные userMessage.', evidence=r'202|accepted|tracking|status endpoint|userMessage'),

    # ----------------------- external and files ---------------------------
    dict(code='EXT-001', scope='external', area='Внешние зависимости', title='Должен быть known-degradation сценарий.', question='Что показываем или делаем при отказе внешней системы?', why='Внешняя система вне вашего контроля.', how='Опишите fallback, cache/stale data, очередь на повтор, manual review.', evidence=r'fallback|деград|stale|cache|manual'),
    dict(code='EXT-002', scope='external', area='Внешние зависимости', title='Нужно учитывать rate limits и квоты партнёра.', question='Какие лимиты у провайдера и как они мониторятся?', why='Пики нагрузки превратятся в 429 и массовые отказы.', how='Добавьте client-side limiter, очередь, backoff, квоты и алерты.', evidence=r'rate.?limit|quota|429|лимит|квот'),
    dict(code='EXT-003', scope='external', area='Внешние зависимости', title='Нужно status inquiry для неизвестного результата внешней операции.', question='Как узнать, выполнилась ли операция, если ответ потерялся?', why='Повтор без проверки может создать дубль во внешней системе.', how='Используйте idempotency key и отдельный запрос статуса по external operation id.', evidence=r'status inquiry|провер.*статус|external.*operation'),
    dict(code='EXT-004', scope='webhook', area='Внешние зависимости', title='Webhook должен проверять подпись до бизнес-логики.', question='Как проверяется подлинность отправителя?', why='Иначе любой может подделать callback.', how='Проверяйте HMAC/JWT/mTLS, timestamp, nonce и replay window.', evidence=r'hmac|signature|подпис|jwt|mtls|nonce'),
    dict(code='EXT-005', scope='webhook', area='Внешние зависимости', title='Webhook должен иметь защиту от повторной доставки.', question='Как обрабатывается повторный callback с тем же providerEventId?', why='Провайдеры часто отправляют callback повторно.', how='Используйте Inbox с providerEventId+providerCode и идемпотентную обработку.', evidence=r'inbox|providerEventId|dedup|дедуп'),
    dict(code='EXT-006', scope='file_batch', area='Файлы и batch', title='Файловый обмен должен иметь контроль полноты.', question='Как понять, что файл полный, не повреждён и обработан один раз?', why='Файлы часто обрываются, приходят повторно или частично.', how='Используйте manifest, checksum, file marker, atomic rename и idempotent import.', evidence=r'checksum|manifest|marker|atomic|rename|контрольн'),
    dict(code='EXT-007', scope='file_batch', area='Файлы и batch', title='Batch должен иметь окно запуска и rerun policy.', question='Когда batch стартует, что делать при частичном падении и повторном запуске?', why='Повтор batch может задублировать данные или пропустить период.', how='Опишите batch window, watermark, checkpoint, rerun и reconciliation.', evidence=r'batch window|watermark|checkpoint|rerun|перезапуск'),
    dict(code='EXT-008', scope='external', area='Внешние зависимости', title='Договорные SLA внешней системы должны быть отделены от вашего SLA.', question='Какой SLA партнёра и как он влияет на ваш SLO?', why='Нельзя обещать клиенту лучше, чем позволяет критический внешний путь.', how='Согласуйте SLO, error budget, graceful degradation и статусный async flow.', evidence=r'slo|sla|error budget|доступн'),

    # ----------------------- highload/performance -------------------------
    dict(code='PERF-001', scope='highload', area='Производительность', title='Нужен расчёт peak load, а не только average.', question='Какой пик RPS, burst, размер payload и длительность пика?', why='Система падает на всплесках, а не на среднем значении.', how='Укажите avg/peak RPS, burst, payload size, concurrency и capacity margin.', evidence=r'peak|пик|burst|rps|payload|concurrency'),
    dict(code='PERF-002', scope='highload', area='Производительность', title='Нужно оценить consumer lag.', question='Какой допустимый lag и сколько времени нужно на догон после простоя?', why='Лаг превращает near-real-time процесс в batch.', how='Считайте throughput producer/consumer, partitions, processing time и recovery time.', evidence=r'lag|consumer lag|партиц|throughput'),
    dict(code='PERF-003', scope='highload', area='Производительность', title='Нужны backpressure и shedding.', question='Что происходит при перегрузке: очередь, отказ, деградация или сброс необязательной работы?', why='Без явной политики перегрузка распространяется по цепочке.', how='Опишите queue limits, rate limit, circuit breaker, graceful degradation и shed optional work.', evidence=r'backpressure|shedding|queue limit|деград|rate'),
    dict(code='PERF-004', scope='db', area='Производительность', title='Индексы должны соответствовать реальным запросам.', question='Какие SELECT/UPDATE выполняются на горячем пути?', why='Неверный индекс на высоком RPS превращает БД в bottleneck.', how='Сопоставьте lookup keys с индексами, проверьте EXPLAIN и нагрузочный тест.', evidence=r'index|индекс|explain|query plan'),
    dict(code='PERF-005', scope='db', area='Производительность', title='Нужно контролировать рост таблиц.', question='Как растут entity, outbox, inbox, audit, DLQ и step_log?', why='Служебные таблицы незаметно становятся самыми большими.', how='Опишите retention, partitioning, archiving, vacuum/cleanup и monitoring size.', evidence=r'retention|partition|archive|cleanup|vacuum|ttl'),
    dict(code='PERF-006', scope='read', area='Производительность', title='Горячее чтение должно иметь кэш или read-model.', question='Читает ли быстрый API несколько источников на каждом запросе?', why='Горячий fan-out создаёт высокий latency и отказоустойчивость худшей зависимости.', how='Используйте cache/read-model/materialized view и freshness contract.', evidence=r'cache|кэш|read.?model|projection|материализ'),
    dict(code='PERF-007', scope='highload', area='Производительность', title='Нужно тестировать деградацию, а не только happy throughput.', question='Что происходит при падении БД, росте latency внешней системы и переполнении DLQ?', why='Нагрузочный тест без отказов не показывает устойчивость.', how='Добавьте soak, spike, stress, failover, chaos и replay-load tests.', evidence=r'soak|spike|stress|chaos|failover|нагруз'),
    dict(code='PERF-008', scope='kafka', area='Производительность', title='Количество партиций должно соответствовать параллелизму и ordering.', question='Сколько партиций нужно и почему?', why='Мало партиций ограничивает throughput, слишком много усложняет эксплуатацию.', how='Рассчитайте partitions по target throughput, consumer concurrency и ordering key.', evidence=r'partition|партиц|consumer concurrency'),

    # ----------------------- security/privacy -----------------------------
    dict(code='SEC-001', scope='security', area='Безопасность', title='Все входы должны быть аутентифицированы и авторизованы.', question='Кто имеет право вызвать API, отправить событие или загрузить файл?', why='Интеграции часто становятся обходным путём авторизации.', how='Используйте mTLS/OAuth/JWT/service accounts, ACL topics, RBAC и least privilege.', evidence=r'auth|oauth|jwt|mtls|acl|rbac|авторизац|аутентиф'),
    dict(code='SEC-002', scope='sensitive', area='Безопасность', title='ПДн и секреты не должны попадать в логи, DLQ и ошибки.', question='Какие поля маскируются и где запрещены полностью?', why='Технические хранилища часто менее защищены, чем основная БД.', how='Классифицируйте поля, маскируйте логи, очищайте DLQ/outbox, не возвращайте секреты в errorMessage.', evidence=r'mask|маскир|secret|секрет|pii|пдн|dlq'),
    dict(code='SEC-003', scope='sensitive', area='Безопасность', title='Должна быть политика retention для чувствительных данных.', question='Сколько хранить ПДн в основной БД, логах, outbox, inbox, DWH и бэкапах?', why='Без retention данные остаются навсегда во вспомогательных местах.', how='Опишите TTL, archive, deletion, anonymization и исключения для аудита.', evidence=r'retention|ttl|анонимиз|удален|erasure|хранени'),
    dict(code='SEC-004', scope='security', area='Безопасность', title='Нужна защита от replay-атак.', question='Можно ли повторить старый запрос/webhook и снова применить операцию?', why='Подписанный, но старый callback может быть переиспользован.', how='Проверяйте timestamp, nonce, signature и idempotency window.', evidence=r'nonce|timestamp|signature|replay attack|окно'),
    dict(code='SEC-005', scope='security', area='Безопасность', title='Секреты интеграций должны ротироваться.', question='Как ротируются API keys, HMAC secrets, certificates и service tokens?', why='Неротируемый секрет превращает утечку в постоянный доступ.', how='Используйте secret manager, версии секретов, overlap window и runbook ротации.', evidence=r'secret manager|rotation|ротац|certificate|сертификат'),
    dict(code='SEC-006', scope='dwh', area='Безопасность', title='DWH/витрина не должны расширять доступ к ПДн.', question='Кто видит данные после выгрузки в аналитику?', why='Аналитический контур часто имеет больше пользователей.', how='Минимизируйте поля, обезличивайте, применяйте RBAC/ABAC и audit queries.', evidence=r'аноним|обезлич|rbac|abac|витрин|dwh'),
    dict(code='SEC-007', scope='file_batch', area='Безопасность', title='Файлы должны шифроваться и проверяться.', question='Как шифруется файл, кто имеет доступ и как проверяется целостность?', why='Файл легко скопировать, потерять или подменить.', how='Используйте encryption, signature/checksum, secure transport и lifecycle cleanup.', evidence=r'encrypt|шифр|checksum|подпис|sftp|tls'),
    dict(code='SEC-008', scope='security', area='Безопасность', title='Должна быть защита от injection и schema poisoning.', question='Валидируются ли входные поля до бизнес-логики?', why='Интеграционный payload может содержать неожиданные структуры, SQL/JSON injection и слишком глубокие объекты.', how='Используйте schema validation, allow-list полей, limits на глубину/размер и parameterized queries.', evidence=r'validation|валидац|allow.?list|schema|sql injection'),

    # ----------------------- observability/ops ----------------------------
    dict(code='OBS-001', scope='observability', area='Наблюдаемость', title='CorrelationId должен проходить через всю цепочку.', question='Можно ли по одному id найти API-запрос, события, записи БД, внешние вызовы и DLQ?', why='Без трассировки incident response становится ручным поиском.', how='Пробрасывайте correlationId/traceparent во все логи, события, headers и таблицы.', evidence=r'correlation|trace|tracking|traceparent|корреляц'),
    dict(code='OBS-002', scope='observability', area='Наблюдаемость', title='Нужны бизнес-метрики, а не только технические.', question='Сколько процессов создано, завершено, зависло, отклонено и восстановлено?', why='CPU и latency не показывают, что бизнес-процесс застрял.', how='Добавьте metrics: created/completed/failed/stuck/status_age/replayed/reconciled.', evidence=r'business metric|status_age|completed|failed|метрик'),
    dict(code='OBS-003', scope='async', area='Наблюдаемость', title='Нужны метрики DLQ, retry и replay.', question='Сколько сообщений в DLQ, как долго они там лежат и кто отвечает?', why='DLQ без алертов превращается в кладбище событий.', how='Мониторьте DLQ count/age, retry count, replay success/failure и owner alerts.', evidence=r'dlq|retry|replay|alert|алерт'),
    dict(code='OBS-004', scope='kafka', area='Наблюдаемость', title='Нужен consumer lag per topic/partition/group.', question='Как быстро потребители отстают и догоняют?', why='Lag — главный сигнал деградации потоковой обработки.', how='Добавьте lag dashboard, alert thresholds и runbook масштабирования.', evidence=r'consumer lag|lag|partition|group'),
    dict(code='OBS-005', scope='external', area='Наблюдаемость', title='Нужно отдельно мониторить внешние зависимости.', question='Какой latency, error rate, timeout rate и breaker state у каждого партнёра?', why='Без разреза по партнёру непонятно, кто деградирует.', how='Метрики по dependencyName: latency p95/p99, 4xx/5xx, timeout, 429, breaker.', evidence=r'dependency|external|latency|p95|p99|breaker'),
    dict(code='OBS-006', scope='base', area='Наблюдаемость', title='Логи должны быть структурированными.', question='Есть ли единые поля log для processId, operationId, status, errorCode?', why='Свободный текст плохо ищется и агрегируется.', how='Используйте JSON logs и единый logging contract.', evidence=r'json log|structured|структурир|log'),
    dict(code='OBS-007', scope='operations', area='Эксплуатация', title='Должен быть runbook инцидентов.', question='Что делает поддержка при росте DLQ, зависших статусах, падении внешней системы?', why='Без runbook время восстановления зависит от конкретного человека.', how='Опишите диагностику, команды replay, rollback, escalation и коммуникации.', evidence=r'runbook|инструкц|эскалац|incident|инцидент'),
    dict(code='OBS-008', scope='operations', area='Эксплуатация', title='Алерты должны иметь владельца и порог.', question='Кто получает алерт и какой порог считается нарушением?', why='Алерт без владельца — это шум.', how='Для каждого alert укажите owner, severity, threshold, action и silence policy.', evidence=r'alert|алерт|threshold|порог|owner'),

    # ----------------------- compliance/audit -----------------------------
    dict(code='CMP-001', scope='regulatory', area='Комплаенс и аудит', title='Юридически значимые действия должны иметь append-only audit trail.', question='Можно ли доказать кто, что, когда и почему сделал?', why='Регуляторика и спорные операции требуют доказуемой истории.', how='Пишите append-only audit/event log с actor, reason, payload hash, timestamp.', evidence=r'audit|аудит|append|evidence|журнал'),
    dict(code='CMP-002', scope='money', area='Комплаенс и аудит', title='Финансовые изменения должны быть журналом проводок.', question='Есть ли ledger вместо перезаписи баланса?', why='Перезапись баланса не объясняет происхождение денег.', how='Используйте append-only ledger, immutable operationId и reconciliation.', evidence=r'ledger|проводк|balance|баланс|append'),
    dict(code='CMP-003', scope='regulatory', area='Комплаенс и аудит', title='Регуляторная витрина должна иметь lineage.', question='Из каких источников и версий данных собрана отчётность?', why='Без lineage нельзя объяснить расхождение отчёта.', how='Храните source, extraction time, transformation version, checksum и report period.', evidence=r'lineage|витрин|report|отчет|source|checksum'),
    dict(code='CMP-004', scope='regulatory', area='Комплаенс и аудит', title='Нужно управлять исправлениями отчётных данных.', question='Как корректируются уже отправленные данные?', why='Исправление отчётности без журнала создаёт юридический риск.', how='Используйте correction records, versioned reports и audit reason.', evidence=r'correction|корректир|исправл|versioned report'),
    dict(code='CMP-005', scope='sensitive', area='Комплаенс и аудит', title='Должны быть права доступа на ручной replay и исправления.', question='Кто может переиграть сообщение или изменить статус?', why='Replay — это фактически повторное выполнение бизнес-операции.', how='Ограничьте права, логируйте действия и требуйте reason/approval для опасных операций.', evidence=r'approval|прав|role|rbac|replay'),
    dict(code='CMP-006', scope='regulatory', area='Комплаенс и аудит', title='Нужно учитывать хранение доказательств после удаления ПДн.', question='Как совместить право на удаление и обязательный аудит?', why='Часть данных нужно удалить, а часть сохранить как evidence.', how='Разделите ПДн и audit hash/evidence, применяйте anonymization и legal hold.', evidence=r'legal hold|erasure|аноним|hash|evidence'),

    # ----------------------- migration/deployment -------------------------
    dict(code='MIG-001', scope='legacy', area='Внедрение и миграция', title='Переход со старой системы должен иметь cutover plan.', question='Когда переключаем трафик и какие критерии успеха?', why='Без cutover можно потерять незавершённые процессы.', how='Опишите feature flags, migration window, freeze, smoke tests и rollback criteria.', evidence=r'cutover|feature flag|freeze|rollback|миграц'),
    dict(code='MIG-002', scope='legacy', area='Внедрение и миграция', title='Нужен dual-run или shadow mode для рискованных миграций.', question='Как сравниваются старый и новый путь до переключения?', why='Без параллельной проверки ошибки проявятся только после cutover.', how='Запустите shadow/dual-run, сравните результаты и заведите diff report.', evidence=r'dual.?run|shadow|parallel|параллельн|diff'),
    dict(code='MIG-003', scope='migration', area='Внедрение и миграция', title='Старые незавершённые процессы должны быть мигрированы или добиты старым путём.', question='Что делать с заявками в PROCESSING на момент релиза?', why='In-flight процессы часто ломаются при смене контракта или маршрута.', how='Опишите migration of in-flight, compatibility layer или drain old flow.', evidence=r'in.?flight|незаверш|drain|backfill|миграц'),
    dict(code='MIG-004', scope='events', area='Внедрение и миграция', title='Контракт должен поддерживать rolling deployment.', question='Могут ли старая и новая версии producer/consumer работать одновременно?', why='В production версии обновляются не мгновенно.', how='Сначала добавляйте optional fields, затем обновляйте consumers, потом делайте required.', evidence=r'rolling|backward|forward|compatible|совместим'),
    dict(code='MIG-005', scope='base', area='Внедрение и миграция', title='Нужен rollback, который не ломает данные.', question='Можно ли откатить код, если данные уже изменились новой версией?', why='Откат приложения не откатывает схему БД и события.', how='Используйте expand-contract migrations, reversible changes, feature flags и data compatibility.', evidence=r'rollback|откат|expand|contract|feature flag'),
    dict(code='MIG-006', scope='db', area='Внедрение и миграция', title='Миграции БД должны быть backward-compatible.', question='Не сломает ли новая схема старый код?', why='Жёсткие миграции создают downtime и аварии при rollback.', how='Применяйте expand → migrate → contract, nullable first, backfill, then enforce.', evidence=r'expand|contract|backfill|nullable|migration'),

    # ----------------------- DWH/read side --------------------------------
    dict(code='DWH-001', scope='dwh', area='DWH и витрины', title='DWH не должен находиться в core-flow.', question='Останавливает ли аналитика операционный процесс?', why='DWH обычно не рассчитан на операционный SLA.', how='Выгружайте через CDC/ETL после фиксации операции.', evidence=r'cdc|etl|dwh|витрин|аналит'),
    dict(code='DWH-002', scope='dwh', area='DWH и витрины', title='Выгрузка должна иметь контроль полноты.', question='Как понять, что все изменения за период попали в витрину?', why='Технический экспорт не гарантирует бизнесовую полноту.', how='Используйте watermark, counts, checksums, reconciliation и отчёт расхождений.', evidence=r'watermark|checksum|count|сверк|reconciliation'),
    dict(code='DWH-003', scope='dwh', area='DWH и витрины', title='Нужен replay/backfill за период.', question='Можно ли пересобрать витрину за день/месяц после исправления ошибки?', why='Ошибки трансформаций требуют переобработки периода.', how='Храните raw layer, versioned transformations и backfill procedure.', evidence=r'backfill|raw layer|replay|пересбор'),
    dict(code='DWH-004', scope='dwh', area='DWH и витрины', title='Нужно разделять event time и load time.', question='Отчёт строится по времени события или времени загрузки?', why='Поздние события иначе попадают не в тот период.', how='Храните occurredAt, loadedAt, businessDate и правила late data.', evidence=r'event time|load time|businessDate|late'),
    dict(code='DWH-005', scope='read', area='DWH и витрины', title='Read-model должен иметь freshness contract.', question='Насколько данные могут отставать от источника?', why='Потребитель должен понимать, что читает проекцию, а не источник истины.', how='Показывайте lastUpdatedAt, lag и SLA свежести.', evidence=r'freshness|lastUpdated|lag|актуальн'),

    # ----------------------- testing --------------------------------------
    dict(code='TST-001', scope='base', area='Тестирование', title='Нужен тест happy path.', question='Проверяется ли полный основной сценарий от входа до финального статуса?', why='Без end-to-end проверки интеграция может быть “зелёной” по частям и сломанной целиком.', how='Добавьте E2E тест с проверкой статуса, данных, событий и журналов.', evidence=r'e2e|end.?to.?end|happy path|тест'),
    dict(code='TST-002', scope='async', area='Тестирование', title='Нужен тест дубля сообщения.', question='Что происходит при повторной доставке одного события?', why='Дубли являются нормой для at-least-once.', how='Добавьте тест duplicate event/request и проверку отсутствия дубля бизнес-записи.', evidence=r'duplicate|дубл|dedup|идемпот'),
    dict(code='TST-003', scope='events', area='Тестирование', title='Нужен тест out-of-order/stale события.', question='Что происходит, если старое событие пришло после нового?', why='На потоке порядок не всегда гарантирован.', how='Тестируйте sequence/version и terminal-state guard.', evidence=r'out.?of.?order|stale|sequence|устарев'),
    dict(code='TST-004', scope='external', area='Тестирование', title='Нужен тест timeout внешней системы.', question='Что происходит при timeout, 5xx и 429?', why='Внешние отказы должны быть штатным сценарием.', how='Добавьте contract/mock tests для timeout/5xx/429 и проверку fallback.', evidence=r'timeout|5xx|429|mock|contract'),
    dict(code='TST-005', scope='async', area='Тестирование', title='Нужен тест DLQ и replay.', question='Можно ли безопасно восстановить сообщение из DLQ?', why='Восстановление часто ломается, если его не проверять.', how='Автоматизируйте сценарий poison message → DLQ → fix → replay → reconciliation.', evidence=r'dlq|replay|poison'),
    dict(code='TST-006', scope='writes', area='Тестирование', title='Нужен тест конкурентных запросов.', question='Что происходит при двух параллельных операциях по одной сущности?', why='Race condition не виден на одиночном тесте.', how='Добавьте concurrent test на unique/locking/idempotency.', evidence=r'concurrent|race|parallel|параллельн|гонк'),
    dict(code='TST-007', scope='base', area='Тестирование', title='Нужны контрактные тесты.', question='Проверяется ли соответствие producer/consumer или client/server контракту?', why='Изменение обязательного поля часто не ловится unit-тестами.', how='Добавьте consumer-driven contracts, schema compatibility и negative tests.', evidence=r'contract test|pact|schema|consumer'),
    dict(code='TST-008', scope='highload', area='Тестирование', title='Нужен нагрузочный и soak-тест.', question='Система выдерживает длительный поток и пики?', why='Короткий тест не показывает утечки, рост лагов и таблиц.', how='Проведите load, stress, spike, soak и recovery tests.', evidence=r'load test|stress|spike|soak|нагруз'),
    dict(code='TST-009', scope='security', area='Тестирование', title='Нужны негативные тесты безопасности.', question='Проверяются ли неверная подпись, чужой tenant, истёкший токен, превышение размера?', why='Happy path не доказывает безопасность.', how='Добавьте negative security tests для auth, signature, ACL, PII leakage и input limits.', evidence=r'security test|negative|неверн.*подпис|auth'),
    dict(code='TST-010', scope='migration', area='Тестирование', title='Нужно тестировать rollback и совместимость версий.', question='Проверен ли откат после частичной миграции?', why='Rollback часто ломается из-за несовместимых данных.', how='Тестируйте rolling deploy, old/new compatibility, feature flag off и data rollback plan.', evidence=r'rollback|rolling|compat|feature flag'),
]


def _context(model):
    meta = model.get('meta') or {}
    steps = model.get('steps') or []
    systems = model.get('systems') or {}
    graph = model.get('graph') or {}
    channels = {s.get('channel') for s in steps}
    roles = {v.get('role') for v in systems.values()}
    blob = _blob(model)
    has_sensitive = bool(meta.get('regulatory') or any(f.get('sensitive') for f in meta.get('fields', [])) or re.search(r'пдн|паспорт|email|телефон|secret|секрет|personal|sensitive', blob))
    has_db = 'db' in channels or 'db' in roles or any(s.get('writes_entity') for s in steps)
    return {
        'base': True,
        'data': bool(meta.get('fields') or meta.get('lookup_keys') or any(s.get('writes_entity') for s in steps)),
        'writes': any(s.get('writes_entity') for s in steps),
        'events': bool(channels & {'ibm_mq', 'redis_streams', 'rabbitmq', 'gcp_pubsub', 'queue', 'callback', 'activemq', 'websocket', 'redis_queue', 'mqtt', 'webhook', 'sns_sqs', 'sse', 'nats', 'kafka', 'pulsar', 'azure_service_bus'}),
        'kafka': 'kafka' in channels,
        'async': bool(graph.get('async_steps')) or bool(channels & {'callback', 'batch', 'clickhouse', 'lakehouse', 'spark', 'nats', 'cdc', 'redis_streams', 'cassandra', 'gcp_pubsub', 'queue', 'sftp', 'workflow_engine', 'sns_sqs', 'kafka', 'pulsar', 'azure_service_bus', 'ibm_mq', 'data_lake', 'activemq', 'data_warehouse', 'etl', 'airflow', 'rabbitmq', 'sse', 'object_storage', 'dbt', 'file', 'observability', 'websocket', 'redis_queue', 'mqtt', 'webhook', 'bpm_engine'}),
        'sync': any(s.get('blocking') and s.get('channel') in {'search', 'cdn', 'mongodb', 'vector_db', 'grpc', 'service_mesh', 'api_gateway', 'db', 'graphql', 'vault', 'esb', 'dynamodb', 'redis_cache', 'read_replica', 'db_sharding', 'memcached', 'rest', 'auth_oidc', 'odata', 'redis_lock', 'soap'} for s in steps),
        'external': bool(graph.get('external_blocking')) or 'external' in roles,
        'webhook': bool(channels & {'webhook', 'callback', 'websocket', 'sse'}),
        'file_batch': bool(channels & {'file', 'batch', 'sftp', 'etl', 'spark', 'airflow', 'object_storage', 'dbt'}),
        'money': meta.get('money') == 'direct',
        'regulatory': bool(meta.get('regulatory')),
        'sensitive': has_sensitive,
        'highload': int(meta.get('peak_rps') or 0) >= 1000 or int(meta.get('load_rps') or 0) >= 500,
        'customer': bool(meta.get('customer_visible')),
        'multitenant': bool(meta.get('multi_tenant')) or bool(re.search(r'tenant|мультитенант|multi.?tenant', blob)),
        'legacy': bool(meta.get('replacing_legacy')) or 'legacy' in roles or bool(re.search(r'legacy|легаси|миграц|замен', blob)),
        'dwh': 'analytics' in roles or 'cdc' in channels or bool(re.search(r'dwh|витрин|аналит|warehouse|cdc|etl', blob)),
        'read': meta.get('read_freq') in {'high', 'very_high'} or bool(re.search(r'read.?model|projection|кэш|cache|чтени', blob)),
        'db': has_db,
        'migration': bool(meta.get('replacing_legacy')) or bool(re.search(r'migration|миграц|cutover|rollback|legacy|релиз|deploy', blob)),
        'security': True,
        'observability': len({s.get('system') for s in steps}) >= 2 or bool(channels & {'ibm_mq', 'redis_streams', 'rabbitmq', 'gcp_pubsub', 'queue', 'callback', 'activemq', 'websocket', 'redis_queue', 'mqtt', 'webhook', 'sns_sqs', 'sse', 'nats', 'kafka', 'pulsar', 'azure_service_bus'}),
        'operations': True,
    }


def universal_invariant_probes(model, findings=None, patterns=None, completeness=None):
    ctx = _context(model)
    blob = _blob(model)
    fired = {f.get('rule') for f in (findings or [])}
    probes = []

    # Правила ядра, которые должны переводить близкие инварианты в fail.
    fail_hints = {
        'ID-001': {'ambiguous_composite_business_key', 'generic_identifier_scope_ambiguity', 'missing_key_scope_for_shared_dispatcher'},
        'ID-002': {'ambiguous_composite_business_key', 'retry_without_idempotency'},
        'CON-001': {'event_core_fields'},
        'CON-002': {'contract_versioning'},
        'CON-003': {'api_error_contract'},
        'SCN-003': {'status_model'},
        'DAT-001': {'multiple_writers', 'money_controls'},
        'DAT-002': {'dual_write'},
        'DAT-003': {'callback_inbox', 'retry_without_idempotency'},
        'DAT-005': {'saga_without_compensation'},
        'ASY-001': {'async_without_recovery', 'poison_retry'},
        'ASY-004': {'ordering'},
        'API-001': {'missing_timeouts'},
        'API-003': {'external_blocking', 'unstable_dependency'},
        'EXT-004': {'inbound_security'},
        'DWH-001': {'analytics_in_core'},
        'PERF-002': {'stream_consumer_controls', 'stream_ingestion'},
        'OBS-001': {'no_correlation_id', 'observability_missing'},
        'CMP-001': {'regulatory_audit'},
    }

    for inv in INVARIANT_CATALOG:
        if not ctx.get(inv['scope'], False):
            continue
        status = 'ok' if re.search(inv.get('evidence') or r'$', blob) else inv.get('missing_status', 'unknown')
        if inv['scope'] in {'external', 'async', 'kafka', 'webhook', 'money', 'regulatory', 'sensitive', 'highload', 'security'} and status == 'unknown':
            status = 'warn'
        if fired & fail_hints.get(inv['code'], set()):
            status = 'fail'
        probes.append(_probe(status, inv['area'], inv['title'], inv['question'], inv['why'], inv['how'], inv.get('examples'), inv['code']))
    return probes


def invariant_catalog_stats(model):
    ctx = _context(model)
    applicable = sum(1 for inv in INVARIANT_CATALOG if ctx.get(inv['scope'], False))
    return {'total': len(INVARIANT_CATALOG), 'applicable': applicable}
