import json
import os

import pytest

from ui_browser_test_helpers import active_step, chromium_page, click_next, hidden_json, running_app, start_flow

pytestmark = pytest.mark.skipif(os.environ.get('RUN_BROWSER_TESTS') != '1', reason='browser test requires RUN_BROWSER_TESTS=1')


def test_all_business_first_buttons_and_restart_browser():
    with running_app() as url, chromium_page(url) as (page, js_errors):
        start_flow(page)
        for case in ['data_change_distribution', 'external_check', 'data_enrichment', 'status_screen']:
            page.locator(f"[data-business-case='{case}']").click()
            assert 'is-active' in page.locator(f"[data-business-case='{case}']").get_attribute('class')
            assert page.locator('#businessCaseHidden').input_value() == case
            assert page.locator('#simpleSituationHidden').input_value().strip()
            assert page.locator('#autoGeneratedTechnicalChainJson').input_value().strip()
        click_next(page, 1)
        page.locator('#constructorPrev').click()
        page.locator("section.constructor-screen.is-active[data-constructor-screen='0']").wait_for()
        click_next(page, 1)

        page.locator('#addBusinessActorBtn').click()
        page.locator('#businessActorRole').select_option(label='Внутренняя система')
        page.locator('#addBusinessActorBtn').click()
        page.locator('#addBusinessStepBtn').click()
        page.locator('#businessStepAction').select_option(label='Обновляет статус')
        page.locator('#addBusinessStepBtn').click()
        assert page.locator('#businessActorList .participant-card').count() >= 2
        assert page.locator('#businessStepList .business-step-card').count() >= 2
        before_order = page.locator('#businessStepsJson').input_value()
        page.locator('#businessStepList .business-step-card').nth(0).locator('[data-step-down]').click()
        assert page.locator('#businessStepsJson').input_value() != before_order
        page.locator('#businessStepList .business-step-card').nth(1).locator('[data-step-up]').click()
        page.locator('#businessStepList .business-step-card').nth(0).locator('[data-step-edit]').click()
        assert page.locator('#addBusinessStepBtn').inner_text() == 'Сохранить шаг'
        page.locator('#businessStepAction').select_option(label='Передаёт данные дальше')
        page.locator('#addBusinessStepBtn').click()
        assert page.locator('#addBusinessStepBtn').inner_text() == '+ Добавить шаг процесса'
        page.locator('#businessStepList .business-step-card').last.locator('[data-step-delete]').click()
        page.locator('#businessActorList .participant-card').last.locator('[data-del-ba]').click()
        page.locator("[data-business-preset='deferred_application']").click()
        assert page.locator('#businessStepList .business-step-card').count() >= 4
        for selector in ['#businessActorsJson', '#businessStepsJson', '#businessProcessJson', '#autoGeneratedTechnicalChainJson', '#processGraphJson']:
            hidden_json(page, selector)
        assert 'Бизнес-процесс' in page.locator('#businessPreview').inner_text()

        click_next(page, 2)
        page.locator('#businessObjectSelect').select_option(label='Договор')
        page.locator('#businessTimingSelect').select_option(label='Можно позже')
        page.locator("input[name='constraint_flags'][value='pii']").check()
        page.locator("input[name='constraint_flags'][value='manual']").check()
        constraints = json.loads(page.locator('#businessConstraintsJson').input_value())
        assert {'pii', 'manual'} <= set(constraints)
        click_next(page, 3)
        assert 'Бизнес-процесс' in page.locator('#autoSchemeReview').inner_text()
        step_before = active_step(page)
        business_steps_before = page.locator('#businessStepsJson').input_value()
        custom_before = page.locator('#customChainJson').input_value()
        page.locator('#openTechnicalConstructor').click()
        assert active_step(page) == step_before
        assert page.locator('#technicalConstructorDetails').evaluate('e => e.open')
        assert page.locator('#businessStepsJson').input_value() == business_steps_before
        assert page.locator('#customChainJson').input_value() == custom_before
        click_next(page, 4)
        page.locator('#openTechnicalConstructorReview').click()
        assert active_step(page) == '4'
        assert page.locator('#technicalConstructorDetails').evaluate('e => e.open')
        page.locator('#confirmUnderstanding').click()
        page.locator("section.constructor-screen.is-active[data-constructor-screen='5']").wait_for()
        assert page.locator('#constructorNav').evaluate("e => getComputedStyle(e).display") == 'none'
        for text in ['Бизнес-процесс', 'Схема взаимодействия', 'Почему выбрана такая техническая схема', 'Что обязательно сделать', 'Главные риски', 'Что отдать разработке']:
            assert page.get_by_text(text).first.is_visible()
        page.locator('#submitBtn').click()
        page.wait_for_load_state('networkidle')
        body = page.locator('body').inner_text()
        for text in ['Бизнес-процесс', 'Схема взаимодействия', 'Почему выбрана такая техническая схема', 'Что обязательно сделать', 'Главные риски', 'Что отдать разработке']:
            assert text in body
        page.goto(url, wait_until='networkidle')
        start_flow(page)
        click_next(page, 1)
        page.locator('#addBusinessActorBtn').click()
        page.locator('#backToStart').click()
        assert page.locator('#startScreen').is_visible()
        page.locator('#startNoTextBtn').click()
        page.locator("section.constructor-screen.is-active[data-constructor-screen='0']").wait_for()
        click_next(page, 1)
        page.locator('#addBusinessStepBtn').click()
        assert page.locator('#businessStepsJson').input_value().strip()
        assert not js_errors


def test_auto_scheme_uses_default_business_process_without_manual_steps_browser():
    with running_app() as url, chromium_page(url) as (page, js_errors):
        start_flow(page, 'application_creation')
        click_next(page, 1)
        assert page.locator('#businessStepsJson').input_value() == '[]'
        click_next(page, 2)
        click_next(page, 3)
        auto_text = page.locator('#autoSchemeReview').inner_text()
        assert 'Клиент создаёт заявку → система принимает → обработка выполняется позже → статус обновляется' in auto_text
        assert 'Бизнес-процесс' in auto_text
        assert not js_errors
