import os
import socket
import subprocess
import sys
import time
from contextlib import closing
from urllib.request import urlopen

import pytest

pytestmark = pytest.mark.skipif(os.environ.get('RUN_BROWSER_TESTS') != '1', reason='browser test requires RUN_BROWSER_TESTS=1')


def _free_port():
    with closing(socket.socket(socket.AF_INET, socket.SOCK_STREAM)) as sock:
        sock.bind(('127.0.0.1', 0))
        return sock.getsockname()[1]


def _wait(url, proc, timeout=20):
    deadline = time.time() + timeout
    last = None
    while time.time() < deadline:
        if proc.poll() is not None:
            raise RuntimeError(f'server exited: {proc.returncode}')
        try:
            with urlopen(url, timeout=1) as r:
                if r.status == 200:
                    return
        except Exception as e:
            last = e
        time.sleep(0.2)
    raise RuntimeError(f'not started: {last}')


def test_business_first_constructor_in_real_chromium():
    from playwright.sync_api import sync_playwright, Error as PlaywrightError
    port = _free_port()
    env = os.environ.copy(); env.update({'HOST':'127.0.0.1','PORT':str(port)})
    proc = subprocess.Popen([sys.executable, 'integration_architect_pro.py'], stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True, env=env)
    try:
        url=f'http://127.0.0.1:{port}/'
        _wait(url, proc)
        errors=[]
        with sync_playwright() as pw:
            
            try:
                browser = pw.chromium.launch(headless=True)
            except PlaywrightError as exc:
                pytest.skip(f'Chromium executable is not installed in this environment: {exc}')
            page = browser.new_page()
            page.on('console', lambda msg: errors.append(msg.text) if msg.type == 'error' else None)
            page.on('pageerror', lambda exc: errors.append(str(exc)))
            page.goto(url, wait_until='networkidle')
            start = page.locator('#startScreen').inner_text()
            for forbidden in ['Kafka','Outbox','Inbox','DB','Worker','REST','BFF','Cache']:
                assert forbidden not in start
            page.get_by_role('button', name='Начать').click()
            page.locator('#constructorNext').click()
            page.locator("section.constructor-screen.is-active[data-constructor-screen='1']").wait_for()
            page.locator('#addBusinessActorBtn').click()
            page.locator('#addBusinessStepBtn').click()
            assert '1 участников' in page.locator('#businessActorCounter').inner_text()
            assert '1 шагов' in page.locator('#businessStepCounter').inner_text()
            assert page.locator('#businessProcessJson').input_value().strip()
            assert page.locator('#autoGeneratedTechnicalChainJson').input_value().strip()
            assert not page.locator('#technicalConstructorDetails').evaluate('e => e.open')
            page.locator('#constructorNext').click()
            page.locator("section.constructor-screen.is-active[data-constructor-screen='2']").wait_for()
            page.locator('#constructorNext').click()
            page.locator("section.constructor-screen.is-active[data-constructor-screen='3']").wait_for()
            assert page.get_by_text('Система построила техническую схему').is_visible()
            step_before = page.locator('section.constructor-screen.is-active').get_attribute('data-constructor-screen')
            page.locator('#openTechnicalConstructor').click()
            assert page.locator('section.constructor-screen.is-active').get_attribute('data-constructor-screen') == step_before
            assert page.locator('#technicalConstructorDetails').evaluate('e => e.open')
            page.locator('#addParticipantBtn').click()
            page.locator('#addParticipantBtn').click()
            page.locator('#addConnectionBtn').click()
            assert page.locator('#customChainJson').input_value().strip()
            page.locator('#constructorNext').click()
            page.locator('#constructorNext').click()
            page.locator('#constructorNext').click()
            page.locator('#constructorNext').click()
            page.locator("section.constructor-screen.is-active[data-constructor-screen='5']").wait_for()
            for text in ['Бизнес-процесс','Схема взаимодействия','Почему выбрана такая техническая схема','Что обязательно сделать','Главные риски','Что отдать разработке']:
                assert page.get_by_text(text).first.is_visible()
            browser.close()
        assert errors == []
    finally:
        proc.terminate()
        try:
            proc.wait(timeout=5)
        except subprocess.TimeoutExpired:
            proc.kill()
